name: Discord Webhook Commit Log
on:
  issue:
    types:
      - opened
      - labeled

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Better Discord Notification
        uses: Retr0-01/better-discord-notification@main
        with:
          webhook-url: ${{ secrets.YOUR_DISCORD_WEBHOOK_URL }}
          embed-color: '12390624'
          footer-icon: 'https://files.facepunch.com/sbox/org/pcjr/logo.a1a6ab6f.png'
